#!/bin/bash

# Define the version file path
VERSION_FILE="js/versionData.js"

# Check if commit message is provided
if [ -z "$1" ]; then
    echo "Error: No commit message provided."
    echo "Usage: ./deploy.sh \"Your commit message\""
    exit 1
fi

COMMIT_MSG="$1"

# Read current version
# Extract the value part after 'version:', remove quotes, commas, and whitespace
CURRENT_VERSION=$(grep 'version:' "$VERSION_FILE" | sed -E 's/.*version: *"([^"]+)".*/\1/' | sed 's/[, ]//g')

# Logic to increment version
if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    # Semantic Versioning (X.Y.Z) -> Increment Z
    IFS='.' read -r -a parts <<< "$CURRENT_VERSION"
    major=${parts[0]}
    minor=${parts[1]}
    patch=${parts[2]}
    new_patch=$((patch + 1))
    NEW_VERSION="$major.$minor.$new_patch"
else
    # Fallback/Integer: just increment
    NEW_VERSION=$((CURRENT_VERSION + 1))
fi

CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")

# Write new content to versionData.js
cat > "$VERSION_FILE" <<EOF
// This file is auto-generated by deploy.sh
export const versionData = {
    version: "$NEW_VERSION",
    lastUpdated: "$CURRENT_DATE"
};
EOF

echo "Version bumped to $NEW_VERSION"
echo "Timestamp updated to $CURRENT_DATE"

# Git operations
git add .
git commit -m "[v$NEW_VERSION] $COMMIT_MSG"
git push

echo "Deployed successfully!"
