#!/bin/bash

# Define the version file path
VERSION_FILE="js/versionData.js"

# Read current version
# Extract the value part after 'version:', remove quotes, commas, and whitespace
CURRENT_VERSION=$(grep 'version:' "$VERSION_FILE" | sed -E 's/.*version: *"([^"]+)".*/\1/' | sed 's/[, ]//g')

# Logic to increment version
if [[ "$CURRENT_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    # Semantic Versioning (X.Y.Z) -> Increment Z
    IFS='.' read -r -a parts <<< "$CURRENT_VERSION"
    major=${parts[0]}
    minor=${parts[1]}
    patch=${parts[2]}
    new_patch=$((patch + 1))
    NEW_VERSION="$major.$minor.$new_patch"
else
    # Fallback/Integer: just increment
    NEW_VERSION=$((CURRENT_VERSION + 1))
fi

CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")

# Write new content to versionData.js
cat > "$VERSION_FILE" <<EOF
// This file is auto-generated by scripts/update-version.sh
export const versionData = {
    version: "$NEW_VERSION",
    lastUpdated: "$CURRENT_DATE"
};
EOF

echo "Auto-bump: Version updated to $NEW_VERSION"
